name: Test Xdebug Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Chromium
        run: sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Install dependencies (test directory)
        working-directory: ./test
        run: npm install

      - name: Run Tests
        working-directory: ./test
        run: BROWSER_PATH=/usr/bin/chromium-browser npm test

      # - name: Upload test artifacts (optional)
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: ./test/test-reports/*
      #     retention-days: 1
